In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing


In [2]:
df=pd.read_csv('play_or_not.csv')
df

weather  temp  play
0      sunny   Hot    No
1      sunny   Hot    No
2   overcast   Hot   Yes
3      rainy  Mild   Yes
4      rainy  Cool  Yes 
5      rainy  Cool    No
6   overcast  Cool   Yes
7      sunny  Mild    No
8      sunny  Cool   Yes
9      rainy  Mild   Yes
10     sunny  Mild   Yes
11  overcast  Mild   Yes
12  overcast   Hot   Yes
13     rainy  Mild    No

In [3]:
#creating labelEncoder
le=preprocessing.LabelEncoder()

#converting string labels into numbers
weather_encoded=le.fit_transform(df['weather'])
print(weather_encoded)


[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [4]:
#converting string labels into numbers
temp_encoded=le.fit_transform(df['temp'])
print(temp_encoded)

label=le.fit_transform(df['play'])
print(label)

#combining weather and temp into single listof tuples
features=list(zip(weather_encoded, temp_encoded))
print(features)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 2 0 1 0 1 1 1 1 1 0]
[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2)]


Caveat: If you do not convert them to tuples or another array-like structure and try to pass just the two lists directly to an algorithm, the algorithm may not know how the elements in the two lists correspond to each other or how they form the individual instances or samples.

In [5]:
#Let's build our KNN classifier model
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=3)

#Train the model using the training sets
model.fit(features,label)


[1]


In [6]:
# Get user input with instructions
print("Enter weather conditions:")
print("0: Overcast")
print("1: Rainy")
print("2: Sunny")
weather_input = int(input("Enter weather value (0, 1, or 2): "))

print("\nEnter temperature:")
print("0: Cool")
print("1: Hot")
print("2: Mild")
temp_input = int(input("Enter temperature value (0, 1, or 2): "))

# Predict output
predicted = model.predict([[weather_input, temp_input]])

# Print prediction
if predicted[0] == 1:
    print("\nPrediction: Play")
else:
    print("\nPrediction: Don't Play")

Enter weather conditions:
0: Overcast
1: Rainy
2: Sunny
Enter weather value (0, 1, or 2): 0

Enter temperature:
0: Cool
1: Hot
2: Mild
Enter temperature value (0, 1, or 2): 1

Prediction: Play


We skip the precision, recall, and f1 score due to limited data size.